"""
A2A skills server for Coordinator agent.
Exposes the assign_incident_tasks skill.
"""

import logging
from typing import Any

from common.models import Task, TaskAssignmentResponse
from common.llm_stub import incident_to_tasks
from common.langgraph_state import create_coordinator_state, log_state_message

logger = logging.getLogger(__name__)


class CoordinatorSkillsServer:
    """
    Exposes Coordinator skills via A2A protocol.
    """
    
    def __init__(self):
        """Initialize coordinator skills server."""
        self.state_store = {}  # Simple in-memory store per incident_id
    
    def assign_incident_tasks(self, incident_text: str, incident_id: str) -> TaskAssignmentResponse:
        """
        A2A skill: Assign tasks to an incident using stub LLM.
        
        This skill:
        1. Takes incident text as input
        2. Uses stub LLM to generate 2-3 tasks
        3. Stores local state in LangGraph format
        4. Returns incident_id and tasks to caller
        
        Args:
            incident_text: Description of the incident
            incident_id: Unique incident ID (generated by caller)
            
        Returns:
            TaskAssignmentResponse with incident_id and tasks
        """
        logger.info(f"assign_incident_tasks called: incident_id={incident_id}, text={incident_text[:50]}...")
        
        # Initialize local LangGraph state
        state = create_coordinator_state(incident_id, incident_text)
        self.state_store[incident_id] = state
        
        # Call stub LLM to generate tasks
        tasks = incident_to_tasks(incident_text)
        state["tasks"] = tasks
        state["status"] = "assigned"
        
        log_state_message(state, f"Generated {len(tasks)} tasks via stub LLM")
        logger.info(f"Generated {len(tasks)} tasks for incident {incident_id}")
        
        return TaskAssignmentResponse(incident_id=incident_id, tasks=tasks)
    
    def get_incident_state(self, incident_id: str) -> dict:
        """
        Internal helper to retrieve local state for an incident.
        Used for monitoring/debugging.
        
        Args:
            incident_id: Unique incident identifier
            
        Returns:
            Current incident state or empty dict if not found
        """
        return self.state_store.get(incident_id, {})
