"""
A2A skills server for Coordinator agent.
Exposes the assign_incident_tasks skill.
"""

import logging
from typing import Any

from common.models import Task, TaskAssignmentResponse
from common.llm_stub import request_to_tasks
from common.langgraph_state import create_coordinator_state, log_state_message

logger = logging.getLogger(__name__)


class CoordinatorSkillsServer:
    """
    Exposes Coordinator skills via A2A protocol.
    """
    
    def __init__(self):
        """Initialize coordinator skills server."""
        self.state_store = {}  # Simple in-memory store per request_id
    
    def assign_tasks(self, description: str, request_id: str) -> TaskAssignmentResponse:
        """
        A2A skill: Assign tasks to a work request using stub LLM.
        
        This skill:
        1. Takes description as input
        2. Uses stub LLM to generate 2-3 tasks
        3. Stores local state in LangGraph format
        4. Returns request_id and tasks to caller
        
        Args:
            description: Description of the work request
            request_id: Unique request ID (generated by caller)
            
        Returns:
            TaskAssignmentResponse with request_id and tasks
        """
        logger.info(f"assign_tasks called: request_id={request_id}, description={description[:50]}...")
        
        # Initialize local LangGraph state
        state = create_coordinator_state(request_id, description)
        self.state_store[request_id] = state
        
        # Call stub LLM to generate tasks
        tasks = request_to_tasks(description)
        state["tasks"] = tasks
        state["status"] = "assigned"
        
        log_state_message(state, f"Generated {len(tasks)} tasks via stub LLM")
        logger.info(f"Generated {len(tasks)} tasks for request {request_id}")
        
        return TaskAssignmentResponse(request_id=request_id, tasks=tasks)
    
    def get_request_state(self, request_id: str) -> dict:
        """
        Internal helper to retrieve local state for a request.
        Used for monitoring/debugging.
        
        Args:
            request_id: Unique request identifier
            
        Returns:
            Current request state or empty dict if not found
        """
        return self.state_store.get(request_id, {})
